name: Continuous Delivery

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deliver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
  deploy:
    needs: deliver
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
      - name: Display structure of downloaded files
        run: ls -R 

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      # - name: Login to Docker hub
      #   uses: docker/login-action@v4
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Buil and Push
        uses: docker/build-push-action@v6
        with: 
          context: .
          push: false
          tags: user/app:latest